### ISSUE TITLE
Add ability to update sharable groups for selected items with a modal type behavior

### ISSUE THREAD

**Issue by mohit2530** [earmuff-jam/mashed#135]
## General Description
Audience members who are using the selected event would need to allow certain person to act as an admin on their behalf. 

## Acceptance Criteria
1. Build a autocomplete form which can select users from the profile database. this selected user can be granted admin rights.
2. Build the component inside the editing an event feature.
3. Use sharable groups to track this. it might be beneficial to create a sql function and just re-use that function in the backend to see if anyone belongs to the sharable group.
4. Restrict deactivating an event to the members of the sharable groups only. events have attendees which is different.

**Comment by earmuff-jam** [comment]
Utilize the existing leave event button for this. Group this button to display a secondary action of `Share Event` which will in turn open this modal which will allow for users to share the event to the people from the profile section.
