### ISSUE TITLE
Open a new page detailing items / selection for each category / plan

### ISSUE THREAD

**Issue by mohit2530** [earmuff-jam/mashed#180]
## Acceptance Criteria

1. Add ability to open a new page, when the maintenance card is clicked. 

Note: 
This is a new page and needs ux design as it should contain the donut, associated items, list of reports etc. Similar action should happen for categories so abstract this if possible so that we don't have to do the same thing multiple times.

**Comment by mohit2530** [comment]
We should probably have a discussion for the need of this page. Its needed for sure but what are we going to add on it ? users need to update / edit category ? my first thoughts are users can add / edit pictures probably on this new page. view items that fall under this category. use filters, to filter out specific item, or use search like in assets page to view the item. Maybe the top half can be edit category, and bottom half can be filters and viewing items.

whatever we decide we need the similar experience on maintenance plans as well.

**Comment by mohit2530** [comment]
![image](https://github.com/user-attachments/assets/8b54c1bc-d5c0-45bf-ad04-8ebe4ced9d15)

this seems simple and intuitive

**Comment by earmuff-jam** [comment]
![image](https://github.com/user-attachments/assets/178e522e-5bc1-4d3b-8a1a-e83a76864a13)

we have this as a base direction. we should use this and update as required.
