### ISSUE TITLE
[UI] - Add Spooky Styles for Skeleton loaders

### ISSUE THREAD

**Issue by earmuff-jam** [earmuff-jam/mashed#71]

**Comment by earmuff-jam** [comment]
Adding spooky skeletons to all loading components so that they give users the impression that they are being loaded and just is a minute or so away. We use chunks to lazy load using vite. When we were testing for loading the page , we saw that the spinner displayed for until the items were loaded. We love this approach but instead of a single circular loading icon can we have their own loading components since some of the items are just text.

**Comment by mohit2530** [comment]
Profile Page, Home page are complete. we can create another ticket to handle selected events since we started to add storybook to that pr too and it started to become huge.
