### ISSUE TITLE
[UI] - Add spooky styles to Event landing Page

### ISSUE THREAD

**Issue by mohit2530** [earmuff-jam/mashed#73]
## Acceptance Criteria

1. Add spooky styles for the selected event page.
2. Add storybook if necessary and re-use components if possible.

**Comment by earmuff-jam** [comment]
Give other pages a quick check and look please as well. We also have some tour steps for profile page and selected event page.

**Comment by mohit2530** [comment]
It seems that the profile page is decent and the home page is also decent. of course we can continue to improve, but we have huge other enhancements to build. we should focus on that as well. With that said only the selected event page lacks the spooky content. When we are cleaning that up, we should also check other page and don't forget to check TOUR.
