### ISSUE TITLE
Add notes section and inventories for Profile Page

### ISSUE THREAD

**Issue by mohit2530** [earmuff-jam/mashed#76]
## Acceptance Criteria

1. Create mockup for notes section in profile page.
2. Create mockup for inventories section in profile page.

**Comment by earmuff-jam** [comment]
![image](https://github.com/earmuff-jam/mashed/assets/114630634/11093d70-3a2c-4a38-a10b-9e9b4348df22)

**Comment by mohit2530** [comment]
Fields for inventory -

1. product_name
2. price
3. status - published, draft atm - we have ability to add draft to an item inventory fyi.
4. need barcode and sku
5. all audit columns
6. hidden status
7. bought with coupon, add couple sales off %
8. tax % if possible.
9. categorize the items within a list of 10 - 20 categories like item_categories - users cannot create this.

**Comment by mohit2530** [comment]
Fields for note section 

1. title
2. status
3. text like description field
4. archive or delete for status to delete / archive
5. audit cols

**Comment by earmuff-jam** [comment]
We decided with only 4 item categories. they are - 
1. All products
2. Coupons
3. Draft / Published
4. Items with hidden status

**Comment by earmuff-jam** [comment]
Closing this because we have notes in test env and product inventories have their own tickets I believe.
